<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        Transfer Application -
        {{ $application->application_number }}
    </title>

    <style>
        @page {
            margin: 28px 34px 42px 34px;
        }

        * {
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1e293b;
            font-size: 10px;
            line-height: 1.45;
        }

        h1,
        h2,
        h3,
        p {
            margin: 0;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #1e3a8a;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .header h1 {
            font-size: 18px;
            color: #172554;
            margin-bottom: 5px;
        }

        .header h2 {
            font-size: 13px;
            color: #334155;
            font-weight: normal;
        }

        .reference-box {
            margin-top: 12px;
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            padding: 9px;
        }

        .section {
            margin-bottom: 16px;
        }

        .section-title {
            background: #1e3a8a;
            color: white;
            font-size: 11px;
            font-weight: bold;
            padding: 7px 9px;
            margin-bottom: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .details-table td {
            border: 1px solid #cbd5e1;
            padding: 7px;
            vertical-align: top;
        }

        .details-table .label {
            width: 22%;
            background: #f8fafc;
            font-weight: bold;
            color: #475569;
        }

        .preferences-table th {
            background: #e2e8f0;
            border: 1px solid #94a3b8;
            padding: 7px;
            text-align: left;
        }

        .preferences-table td {
            border: 1px solid #cbd5e1;
            padding: 7px;
            vertical-align: top;
        }

        .status {
            display: inline-block;
            background: #dcfce7;
            color: #166534;
            border: 1px solid #86efac;
            padding: 4px 10px;
            font-weight: bold;
        }

        .declaration {
            border: 1px solid #94a3b8;
            background: #f8fafc;
            padding: 10px;
        }

        .signatures {
            margin-top: 36px;
        }

        .signature-cell {
            width: 50%;
            text-align: center;
            padding: 20px 18px 0 18px;
        }

        .signature-line {
            border-top: 1px solid #334155;
            padding-top: 6px;
        }

        .footer {
            position: fixed;
            left: 0;
            right: 0;
            bottom: -25px;
            text-align: center;
            color: #64748b;
            font-size: 8px;
        }

        .page-break {
            page-break-before: always;
        }

        .muted {
            color: #64748b;
        }
    </style>
</head>

<body>
    <div class="footer">
        Generated by Principal Transfer Management System
        on {{ now()->format('Y-m-d H:i') }}
    </div>

    <div class="header">
        <h1>
            Sabaragamuwa Provincial Ministry of Education
        </h1>

        <h2>
            Principal Transfer Application
        </h2>

        <div class="reference-box">
            <strong>Application Number:</strong>
            {{ $application->application_number ?? 'Not assigned' }}

            &nbsp;&nbsp;&nbsp;

            <strong>Status:</strong>
            <span class="status">
                {{ $application->status }}
            </span>
        </div>
    </div>

    <div class="section">
        <div class="section-title">
            Transfer Cycle
        </div>

        <table class="details-table">
            <tr>
                <td class="label">Cycle</td>
                <td>
                    {{ $application->transferCycle?->name ?? '-' }}
                </td>

                <td class="label">Code</td>
                <td>
                    {{ $application->transferCycle?->code ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Transfer Year</td>
                <td>
                    {{ $application->transferCycle?->transfer_year ?? '-' }}
                </td>

                <td class="label">Transfer Type</td>
                <td>
                    {{ $application->transferCycle?->transfer_type ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Submitted Date</td>
                <td colspan="3">
                    {{ $application->submitted_at?->format('Y-m-d H:i') ?? '-' }}
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">
            Principal Information
        </div>

        <table class="details-table">
            <tr>
                <td class="label">Full Name</td>
                <td>
                    {{ $application->principal_name ?? '-' }}
                </td>

                <td class="label">NIC</td>
                <td>
                    {{ $application->nic ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Employee Number</td>
                <td>
                    {{ $application->employee_number ?? '-' }}
                </td>

                <td class="label">Service Grade</td>
                <td>
                    {{ $application->service_grade ?? '-' }}
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">
            Current Appointment
        </div>

        <table class="details-table">
            <tr>
                <td class="label">Current School</td>
                <td colspan="3">
                    {{ $application->currentSchool?->name ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Division</td>
                <td>
                    {{ $application->currentSchool?->division?->name ?? '-' }}
                </td>

                <td class="label">Zone</td>
                <td>
                    {{ $application->currentSchool?->division?->zone?->name ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Designation</td>
                <td>
                    {{ $application->current_designation ?? '-' }}
                </td>

                <td class="label">Appointment Start Date</td>
                <td>
                    {{ $application->current_appointment_start_date?->format('Y-m-d') ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">
                    Service at Current School
                </td>

                <td colspan="3">
                    {{ $application->current_school_service_months ?? 0 }}
                    months
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">
            Transfer Request
        </div>

        <table class="details-table">
            <tr>
                <td class="label">Transfer Reason</td>
                <td colspan="3">
                    {{ $application->transfer_reason ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">Reason Details</td>
                <td colspan="3">
                    {!! nl2br(e($application->reason_details ?? '-')) !!}
                </td>
            </tr>

            <tr>
                <td class="label">Medical Reason</td>
                <td>
                    {{ $application->has_medical_reason ? 'Yes' : 'No' }}
                </td>

                <td class="label">Spouse Employment</td>
                <td>
                    {{ $application->has_spouse_employment_reason ? 'Yes' : 'No' }}
                </td>
            </tr>

            <tr>
                <td class="label">Mutual Transfer</td>
                <td>
                    {{ $application->is_mutual_transfer ? 'Yes' : 'No' }}
                </td>

                <td class="label">
                    Mutual Principal NIC
                </td>

                <td>
                    {{ $application->mutual_principal_nic ?? '-' }}
                </td>
            </tr>

            <tr>
                <td class="label">
                    Principal Remarks
                </td>

                <td colspan="3">
                    {!! nl2br(e($application->principal_remarks ?? '-')) !!}
                </td>
            </tr>
        </table>
    </div>

    <div class="section">
        <div class="section-title">
            School Preferences
        </div>

        <table class="preferences-table">
            <thead>
                <tr>
                    <th style="width: 8%;">Order</th>
                    <th style="width: 34%;">School</th>
                    <th style="width: 18%;">Division</th>
                    <th style="width: 16%;">Zone</th>
                    <th>Reason</th>
                </tr>
            </thead>

            <tbody>
                @forelse(
                    $application->preferences
                    as $preference
                )
                    <tr>
                        <td>
                            {{ $preference->preference_order }}
                        </td>

                        <td>
                            {{ $preference->school?->name ?? '-' }}

                            @if(
                                $preference->school?->census_number
                            )
                                <br>

                                <span class="muted">
                                    Census:
                                    {{ $preference->school->census_number }}
                                </span>
                            @endif
                        </td>

                        <td>
                            {{ $preference->school?->division?->name ?? '-' }}
                        </td>

                        <td>
                            {{ $preference->school?->division?->zone?->name ?? '-' }}
                        </td>

                        <td>
                            {{ $preference->preference_reason ?? '-' }}
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5">
                            No preferences recorded.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="section">
        <div class="section-title">
            Declaration
        </div>

        <div class="declaration">
            I certify that the information provided in this
            transfer application is true and accurate to the
            best of my knowledge.

            <br><br>

            <strong>Declaration Accepted:</strong>
            {{ $application->declaration_accepted ? 'Yes' : 'No' }}

            <br>

            <strong>Submitted At:</strong>
            {{ $application->submitted_at?->format('Y-m-d H:i') ?? '-' }}
        </div>
    </div>

    <table class="signatures">
        <tr>
            <td class="signature-cell">
                <div class="signature-line">
                    Principal Signature
                </div>
            </td>

            <td class="signature-cell">
                <div class="signature-line">
                    Date
                </div>
            </td>
        </tr>
    </table>
</body>
</html>
