<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        Transfer Order
    </title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #111827;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #111827;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }

        .header h1 {
            font-size: 18px;
            margin: 0;
        }

        .header p {
            margin: 4px 0 0;
        }

        .meta {
            width: 100%;
            margin-bottom: 25px;
        }

        .meta td {
            padding: 4px 0;
        }

        .label {
            width: 180px;
            font-weight: bold;
        }

        .content {
            text-align: justify;
        }

        .details {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .details td {
            border: 1px solid #cbd5e1;
            padding: 8px;
        }

        .signature {
            margin-top: 70px;
            text-align: right;
        }

        .footer {
            margin-top: 50px;
            font-size: 10px;
            color: #475569;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>
            SABARAGAMUWA PROVINCIAL MINISTRY OF EDUCATION
        </h1>

        <p>
            Official Principal Transfer Order
        </p>
    </div>

    <table class="meta">
        <tr>
            <td class="label">
                Document Number
            </td>

            <td>
                {{ $document->document_number }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Issued Date
            </td>

            <td>
                {{ $document->issued_date?->format('Y-m-d') }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Application Number
            </td>

            <td>
                {{ $application->application_number }}
            </td>
        </tr>
    </table>

    <p>
        Dear
        <strong>
            {{ $application->principal_name }}
        </strong>,
    </p>

    <div class="content">
        <p>
            Following the decision of the Transfer Board, you are hereby
            transferred from your present appointment to the school stated
            below with effect from the specified date.
        </p>
    </div>

    <table class="details">
        <tr>
            <td class="label">
                NIC
            </td>

            <td>
                {{ $application->nic }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Current School
            </td>

            <td>
                {{ $application->currentSchool?->name }}
            </td>
        </tr>

        <tr>
            <td class="label">
                New School
            </td>

            <td>
                {{ $decision?->recommendedSchool?->name }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Effective Date
            </td>

            <td>
                {{ $decision?->effective_date?->format('Y-m-d') }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Appointment Type
            </td>

            <td>
                {{ $decision?->appointment_type }}
            </td>
        </tr>

        <tr>
            <td class="label">
                Decision Reference
            </td>

            <td>
                {{ $decision?->decision_reference }}
            </td>
        </tr>
    </table>

    <p>
        You are required to assume duties at the new school on the effective
        date and comply with the relevant service and administrative
        regulations.
    </p>

    <div class="signature">
        <p>
            ....................................................
        </p>

        <p>
            Provincial Secretary of Education
        </p>
    </div>

    <div class="footer">
        Generated by the Principal Transfer Management System
    </div>
</body>
</html>
